# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 948eccc512f300660239318c37c2a5600f61c2249e8a19624bccb495a4563f7f7c86ad71dfd8cc3be3286bd89de000ac70b730cbe6f9409e5c64de55c77f5ab5

test:
  secret_key_base: 1065af8404809b29edcdcd6d305623c372f55788f39e9297ab6467f384e6db032b19bcf6bbb782623022eaba80792ea86699d1fe850628adc56ea32d3492c895

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
